/*
 Name: Luther Richardson
 Date: 04/22/2021
 Course: CS-665 Final Project
 Description: Concrete implementation of strategy for searching article databases with LocalDB
*/

package articledatabase.search;

import articledatabase.databases.Article;
import java.util.ArrayList;

public class LocalDbSearch implements ArticleSearch {

  ArrayList<Article> searchResults; // results of the search
  ArrayList<Article> articles; // articles stored in local DB

  /**
   * Constructor for LocalDBSearch.
   *
   * @param articles articles to be searched
   */
  public LocalDbSearch(ArrayList<Article> articles) {
    this.searchResults = new ArrayList<>();
    this.articles = articles;
  }

  /**
   * Search the LocalDB using the given query parameters.
   *
   * @param searchTerm the keyword(s) used for searching the database
   * @param fromDate   the starting date of the query
   * @param toDate     the ending data of the query
   */
  public void searchArticles(String searchTerm, String fromDate, String toDate) {
    // clear results from the last search
    searchResults.clear();

    if (articles.size() > 0) {
      searchTerm = searchTerm.toLowerCase();
      for (Article article : articles) {
        String articleTitle = article.getArticleTitle().toLowerCase();

        if (articleTitle.contains(searchTerm)) {

          int from = Integer.parseInt(fromDate);
          int to = Integer.parseInt(toDate);

          int articleDate = Integer.parseInt(article.getArticleYear());
          if (articleDate >= from && articleDate <= to) {
            searchResults.add(article);
          }
        }
      }
    } else {
      System.out.println("No items to search");
    }
  }

  /**
   * Getter for search results generated by the query.
   *
   * @return list of article titles found via search
   */
  public ArrayList<Article> getSearchResults() {
    return searchResults;
  }
}
